spring.application.name=cland

spring.datasource.url=jdbc:h2:file:./data/cland;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.schema-locations=classpath:jdbc/schema.sql
spring.sql.init.data-locations=classpath:jdbc/data.sql
spring.sql.init.continue-on-error=false

server.port=8080
server.servlet.session.timeout=10m
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.root=INFO
logging.level.edu.vinaenter=DEBUG